title: "TypeScriptの代数的部分型模型"
summary: "TypeScriptの部分型関係がなす代数的構造についての解説、およびその調査記録。"
topics: [typescript, 型システム, 部分型, 代数的構造]
published: true
price: 0
chapters:
  - 1-ast-begin #『はじめに』
  - 2-ast-mental-model #『型のメンタルモデル』
  - 3-ast-algebraic-structures-laws #『代数的構造と代数法則』
  - 4-ast-subtyping-concept #『部分型関係の概念』
  - 5-ast-order-theoretic-model #『順序理論による模型』
  - 6-ast-set-theoretic-model #『集合論による模型』
  - 7-1-ast-lattice-theoretic-model #『束論による模型(1)』
  - 7-2-ast-lattice-theoretic-model-2 #『束論による模型(2)』
  - 8-ast-ring-theoretic-model #『環論による模型』
  - 9-ast-category-theoretic-model #『圏論による模型』
  - x-ast-references #『参考文献』
